In [ ]:
# Import required lib

import numpy as np
import pandas as pd

In [ ]:
# Read csv file

df = pd.read_csv('/content/Google_Stock_Price_Train.csv')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1258 non-null   object 
 1   Open    1258 non-null   float64
 2   High    1258 non-null   float64
 3   Low     1258 non-null   float64
 4   Close   1258 non-null   object 
 5   Volume  1258 non-null   object 
dtypes: float64(3), object(3)
memory usage: 59.1+ KB


In [ ]:
df.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [ ]:
# using important column

train_set = df.iloc[:,1:2].values

In [ ]:
train_set

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

In [ ]:
# Scaling

from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler()
scaled_tr = sc.fit_transform(train_set)

In [ ]:
scaled_tr

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [ ]:
"""
       Input
1 2 3 4 5 6 7 8 9 10  t=3

   x           y
1, 2, 3        4
2, 3, 4        5
3, 4, 5        6
4, 5, 6        7
5, 6, 7        8
6, 7, 8        9
7, 8, 9        10
8, 9, 10       11



"""

In [ ]:
scaled_tr[60-60:60,0]

array([0.08581368, 0.09701243, 0.09433366, 0.09156187, 0.07984225,
       0.0643277 , 0.0585423 , 0.06568569, 0.06109085, 0.06639259,
       0.0614257 , 0.07474514, 0.02797827, 0.02379269, 0.02409033,
       0.0159238 , 0.01078949, 0.00967334, 0.01642607, 0.02100231,
       0.02280676, 0.02273235, 0.02810849, 0.03212665, 0.0433812 ,
       0.04475779, 0.04790163, 0.0440695 , 0.04648783, 0.04745517,
       0.04873875, 0.03936305, 0.04137213, 0.04034898, 0.04784582,
       0.04325099, 0.04356723, 0.04286033, 0.04602277, 0.05398467,
       0.05738894, 0.05714711, 0.05569611, 0.04421832, 0.04514845,
       0.04605997, 0.04412531, 0.03675869, 0.04486941, 0.05065481,
       0.05214302, 0.05612397, 0.05818885, 0.06540665, 0.06882953,
       0.07243843, 0.07993526, 0.07846566, 0.08034452, 0.08497656])

In [ ]:
# Split dependent and independent

x_train=[]
y_train=[]

for i in range(60,1258):
  x_train.append(scaled_tr[i-60:i,0])
  y_train.append(scaled_tr[i,0])

In [ ]:
# Converting list into array

x_train,y_train = np.array(x_train),np.array(y_train)

In [ ]:
x_train.shape

(1198, 60)

In [ ]:
# (1198, 60, 1)

In [ ]:
# Reshape

x_train = np.reshape(x_train,(1198, 60, 1))

In [ ]:
x_train.shape

(1198, 60, 1)

# LSTM Model

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense

In [ ]:
model = Sequential()
model.add(LSTM(50,input_shape=(x_train.shape[1],1),return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50,return_sequences=True))
model.add(LSTM(50))
model.add(Dense(1))

In [ ]:
model.compile(optimizer='adam',loss='mse')

In [ ]:
model.fit(x_train,y_train,epochs=5,batch_size=32)

Epoch 1/5
38/38 [==============================] - 8s 74ms/step - loss: 0.0367
Epoch 2/5
38/38 [==============================] - 3s 74ms/step - loss: 0.0023
Epoch 3/5
38/38 [==============================] - 3s 75ms/step - loss: 0.0021
Epoch 4/5
38/38 [==============================] - 3s 74ms/step - loss: 0.0020
Epoch 5/5
38/38 [==============================] - 3s 74ms/step - loss: 0.0021


In [ ]:
model.save('lstm.h5')

In [ ]:
x_train[100].shape

(60, 1)

In [ ]:
# Testing

y_pred = model.predict(x_train)
y_pred

array([[0.07004238],
       [0.07152713],
       [0.07320557],
       ...,
       [0.9431839 ],
       [0.9466694 ],
       [0.9499306 ]], dtype=float32)

In [ ]:
# Predicted value

y_pred[0:10]

array([[0.07004238],
       [0.07152713],
       [0.07320557],
       [0.07502506],
       [0.07692757],
       [0.07884417],
       [0.08069734],
       [0.08240977],
       [0.08392605],
       [0.08521321]], dtype=float32)

In [ ]:
# Actual value

y_train[0:10]

array([0.08627874, 0.08471612, 0.07454052, 0.07883771, 0.07238262,
       0.06663442, 0.06315574, 0.06782499, 0.06823424, 0.07601012])